apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  labels:
    app.kubernetes.io/name: rbac
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tekton-pipelines
  source:
    repoURL: cnoe://rbac
    targetRevision: HEAD
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      syncOptions:
        - CreateNamespace=true