apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core
  - certmanager

# Don't patch the service to change ClusterIP to NodePort as ports are not exposed on kind
#patches:
#  - path: node-port-patch.yaml
#    target:
#      group: ""
#      version: v1
#      kind: Service
#      name: proxy
