apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex-jobs
  namespace: dex
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dex
  name: dex-jobs-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dex-jobs-role-binding
  namespace: dex
subjects:
  - kind: ServiceAccount
    name: dex-jobs
    namespace: dex
roleRef:
  kind: Role
  name: dex-jobs-role
  apiGroup: rbac.authorization.k8s.io