apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: konflux
type: Opaque
data:
  smee-url: aHR0cHM6Ly9zbWVlLmlvL1dkYXZxOHgwT2M5Sm5sOU0K # https://smee.io/Wdavq8x0Oc9Jnl9M