---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: tekton-pipelines
spec:
  dnsNames:
  - tekton-results-api-service.tekton-pipelines.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: self-signed-cluster-issuer
  secretName: tekton-results-tls
