apiVersion: batch/v1
kind: Job
metadata:
  name: dummy
  namespace: dummy
spec:
  template:
    metadata:
      generateName: dummy
    spec:
      restartPolicy: Never
      containers:
        - name: kubectl
          image: quay.io/ch007m/kubectl:1.31
          command: ["/bin/bash", "-c"]
          env: []
          args:
            - |
              #! /bin/bash
              set +e
              echo "## Print some env vars ..."
              echo "QUAY_ORG: $QUAY_TOKEN"
              set -e