---
apiVersion: v1
kind: Namespace
metadata:
  name: build-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: integration-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipelines-as-code