apiVersion: batch/v1
kind: Job
metadata:
  name: github-app-secrets
  namespace: jobs
spec:
  template:
    metadata:
      generateName: github-app-secrets
    spec:
      serviceAccountName: github-app-secrets-job
      restartPolicy: Never
      containers:
        - name: kubectl
          image: quay.io/ch007m/kubectl:1.31
          command: ["/bin/bash", "-c"]
          env: []
          args:
            - |
              #! /bin/bash
              
              echo "## Saving Github private key to a file"
              echo $GITHUB_PRIVATE_KEY | sed 's/\#/\n/g' > key.tls
              
              set +e
              NS=(pipelines-as-code build-service integration-service)
              for ns in "${NS[@]}"
              do
                echo "### Creating the pipelines-as-code secret for $ns"
                RESULT=$(kubectl create secret generic pipelines-as-code-secret \
                 --namespace=$ns \
                 --from-literal=github-application-id=$GITHUB_APP_ID \
                 --from-literal=webhook.secret=$GITHUB_WEBHOOK_SECRET \
                 --from-file=github-private-key=key.tls 2>&1)
                if [ $? -ne 0 ]; then
                  echo "Kubectl command failed with the following error:"
                  echo "$RESULT"
                  exit 1
                fi
              done
              set -e