apiVersion: batch/v1
kind: Job
metadata:
  name: oauth2-proxysecret
  namespace: konflux-ui
spec:
  template:
    metadata:
      generateName: oauth2-proxysecret
    spec:
      serviceAccountName: konflux-ui-jobs
      restartPolicy: Never
      containers:
        - name: kubectl
          image: quay.io/ch007m/kubectl:1.31
          command: ["/bin/bash", "-c"]
          args:
            - |
              #! /bin/bash
              set +e
              echo "### Creating the oauth2-proxy-client-secret secret"
              RESULT=$(kubectl get secret oauth2-proxy-client-secret -n dex \
                     -o yaml | grep -v '^\s*namespace:\s' \
                     | kubectl apply -n konflux-ui -f - 2>&1)
              if [ $? -ne 0 ]; then
                echo "Kubectl command failed with the following error:"
                echo "$RESULT"
                exit 1
              fi
              
              echo "### Creating the oauth2-proxy-cookie-secret"
              cookie_secret="$(openssl rand -base64 16)"
              RESULT=$(kubectl create secret generic oauth2-proxy-cookie-secret \
                   -n konflux-ui \
                   --from-literal=cookie-secret="$cookie_secret" 2>&1)
              if [ $? -ne 0 ]; then
                echo "Kubectl command failed with the following error:"
                echo "$RESULT"
                exit 1
              fi
              
              set -e