apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd
  labels:
    app.kubernetes.io/name: cluster-issuer
spec:
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://cluster-issuer
    targetRevision: HEAD
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true