apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  labels:
    app.kubernetes.io/name: keycloak
spec:
  destination:
    namespace: keycloak
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: cnoe://keycloak
      targetRevision: HEAD
      path: "crd"
    - repoURL: cnoe://keycloak
      targetRevision: HEAD
      path: "deployment"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true