apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
  labels:
    app.kubernetes.io/name: registry
spec:
  destination:
    namespace: kind-registry
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://registry
    targetRevision: HEAD
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true