apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: tekton-config
spec:
  destination:
    namespace: tekton-operator
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://tekton-config
    targetRevision: HEAD
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true