apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core
  - certmanager

configMapGenerator:
  - name: nginx-idp-location
    files:
      - nginx-idp-location.conf

# Don't patch the service to change ClusterIP to NodePort as ports are not exposed on kind
#patches:
#  - path: node-port-patch.yaml
#    target:
#      group: ""
#      version: v1
#      kind: Service
#      name: proxy
patches:
  - path: nginx-idp-location-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: proxy

namespace: konflux-ui
